#!/bin/bash
title="micro"
frontend="frontend"
theme="default"
for h in themes/$theme/*; do
if [[ -e "$h" ]]; then
if [[ "$h" != "themes/$theme/theme" ]]; then
cp -r $h $frontend
fi
fi
done
for i in content/*/*; do
if [[ -e "$i" ]]; then
source $i
source themes/$theme/theme
if [[ "$(basename $i)" = "home" ]]; then
makeContent > $frontend/index.html
else
makeContent > $frontend/$(basename $i).html
fi
fi
done
