#!/bin/bash


# Define variables for configuration
source core/variables


# Add plugins in codes here
source core/pluginscore


# Copy your theme content except theme file in building directory
source core/themecontent


# Make your site pages
source core/sitepages


# Add myimages directory to building directory
source core/myimagescore
