#!/bin/bash


# Get title for website
while [[ -z "$title" ]]; do
	read -p "Please enter your site title -> " title
	if [[ -z "$title" ]]; then
		echo "Please enter your title"
	fi
done


# Get a directory for website building
read -p "Please enter build address(If you're not sure just click enter) -> " frontend
if [[ -z "$frontend" ]]; then
	frontend="frontend"
	mkdir "$frontend"
fi


# Create necessary directories
mkdir themes content core themes/default themes/default/css themes/default/js plugins





makeTheme () {
	cat <<- _TOKEN_
	makeContent () {
	cat <<- _ECE_
	<!DOCTYPE html>
	<html>
		<head>
			<title>\$title</title>
		</head>
		<body>
			<header>
				<h1>\$title</h1>
				<nav>
					<ul>
						\$(for j in content/*/*; do echo "<li>\$(basename \$j)</li>"; done)
					</ul>
				</nav>
			</header>
			<div>
				\$content
			</div>
			<footer>
			</footer>
		</body>
	</html>
	_ECE_
	}
	_TOKEN_
}
makeTheme > themes/default/theme


makeBuilder () {
	cat <<- _TOKEN_
	#!/bin/bash
	title="$title"
	frontend="$frontend"
	theme="default"
	for h in themes/\$theme/*; do
		if [[ -e "\$h" ]]; then
			if [[ "\$h" != "themes/\$theme/theme" ]]; then
				cp -r \$h \$frontend
			fi
		fi
	done
	for i in content/*/*; do
		if [[ -e "\$i" ]]; then
			source \$i
			source themes/\$theme/theme
			if [[ "\$(basename \$i)" = "home" ]]; then
				makeContent > \$frontend/index.html
			else
				makeContent > \$frontend/\$(basename \$i).html
			fi
		fi
	done
	_TOKEN_
}

makeBuilder > builder && chmod 755 builder && ./builder
