#!/bin/bash


# micro is a static site builder that written with shell script and generally maked for linux operating systems
# LISENCE MIT 2020 Mohammad Ebrahimi
# this is a beta version for developing and should not use for important tasks
# github respiratory: https://github.com/moheb2000/micro



# Get title for website
while [[ -z "$title" ]]; do
	read -p "Please enter your site title -> " title
	if [[ -z "$title" ]]; then
		echo "Please enter your title"
	fi
done


# Get a directory for website building
read -p "Please enter build address(If you're not sure just click enter) -> " frontend
if [[ -z "$frontend" ]]; then
	frontend="frontend"
	mkdir "$frontend"
fi


# Create necessary directories
mkdir themes content core themes/default themes/default/css themes/default/js plugins


# This function creates theme file for default theme
makeTheme () {
	cat <<- _TOKEN_
	makeContent () {
	cat <<- _ECE_
	<!DOCTYPE html>
	<html>
		<head>
			<title>\$title</title>
		</head>
		<body>
			<header>
				<h1>\$title</h1>
				<nav>
					<ul>
						\$(for j in content/*/*; do echo "<li>\$(basename \$j)</li>"; done)
					</ul>
				</nav>
			</header>
			<div>
				\$content
			</div>
			<footer>
			</footer>
		</body>
	</html>
	_ECE_
	}
	_TOKEN_
}

# Save makeTheme in themes/default
makeTheme > themes/default/theme


# Creates builder shell script
makeBuilder () {
	cat <<- _TOKEN_
	#!/bin/bash


	# Define variables for configuration
	title="$title" # This is your site title
	frontend="$frontend" # This is your building directory
	theme="default" # This is your theme name in themes directory


	# Copy your theme content except theme file in building directory
	for h in themes/\$theme/*; do
		if [[ -e "\$h" ]]; then
			if [[ "\$h" != "themes/\$theme/theme" ]]; then
				cp -r \$h \$frontend
			fi
		fi
	done


	# Make your site pages
	for i in content/*/*; do
		if [[ -e "\$i" ]]; then
			source \$i
			source themes/\$theme/theme
			# creat index.html from home file in contents
			if [[ "\$(basename \$i)" = "home" ]]; then
				makeContent > \$frontend/index.html
			else
				makeContent > \$frontend/\$(basename \$i).html
			fi
		fi
	done


	# Add plugins in codes here
	for l in plugins/*; do
		if [[ -e "\$l" ]]; then
			source "\$l"
		fi
	done
	_TOKEN_
}

# Save builder and make it executable and run it for the first time
makeBuilder > builder && chmod 755 builder && ./builder
