#!/bin/bash


# micro is a static site builder that written with shell script and generally maked for linux operating systems
# LISENCE MIT 2020 Mohammad Ebrahimi
# this is a beta version for developing and should not use for important tasks
# github respiratory: https://github.com/moheb2000/micro



# Get title for website
while [[ -z "$title" ]]; do
	read -p "Please enter your site title -> " title
	if [[ -z "$title" ]]; then
		echo "Please enter your title"
	fi
done


# Get a directory for website building
read -p "Please enter build address(If you're not sure just click enter) -> " frontend
if [[ -z "$frontend" ]]; then
	frontend="frontend"
	mkdir "$frontend"
fi


# Create necessary directories
mkdir themes content core themes/default themes/default/css themes/default/js plugins myimages


# This function creates theme file for default theme
makeTheme () {
	cat <<- _TOKEN_
	makeContent () {
	cat <<- _ECE_
	<!DOCTYPE html>
	<html>
		<head>
			<title>\$title</title>
		</head>
		<body>
			<header>
				<h1>\$title</h1>
				<nav>
					<ul>
						\$(for j in content/*/*; do echo "<li>\$(basename \$j)</li>"; done)
					</ul>
				</nav>
			</header>
			<div>
				\$content
			</div>
			<footer>
			</footer>
		</body>
	</html>
	_ECE_
	}
	_TOKEN_
}

# Save makeTheme in themes/default
makeTheme > themes/default/theme


# Create core contents

# Create variables file
makeVariables () {
	cat <<- _TOKEN_
		# Define variables for configuration
		title="$title" # This is your site title
		frontend="$frontend" # This is your building directory
		theme="default" # This is your theme name in themes directory
	_TOKEN_
}
makeVariables > core/variables

# Create themecontent
makeThemeContent () {
	cat <<- _TOKEN_
		# Copy your theme content except theme file in building directory
		for h in themes/"\$theme"/*; do
			if [[ -e "\$h" ]]; then
				if [[ "\$h" != "themes/\$theme/theme" ]]; then
					cp -r "\$h" "\$frontend"
				fi
			fi
		done
	_TOKEN_
}
makeThemeContent >  core/themecontent

# Create sitepages
makeSitePages () {
	cat <<- _TOKEN_
		# Make your site pages
		for i in content/*/*; do
			if [[ -e "\$i" ]]; then
				source "\$i"
				source themes/"\$theme"/theme
				# creat index.html from home file in contents
				if [[ \$(basename "\$i") = "home" ]]; then
					makeContent > "\$frontend"/index.html
				else
					makeContent > "\$frontend"/\$(basename "\$i").html
				fi
			fi
		done
	_TOKEN_
}
makeSitePages > core/sitepages

# Creates myimagescore file
makeMyImagesCore () {
	cat <<- _TOKEN_
		# Add myimages directory to building directory
		if [[ -e myimages ]]; then
			cp -r myimages "\$frontend"
		fi
	_TOKEN_
}
makeMyImagesCore > core/myimagescore

# Create pluginscore file
makePluginsCore () {
	cat <<- _TOKEN_
		# Add plugins in codes here
		for l in plugins/*; do
			if [[ -e "\$l" ]]; then
				source "\$l"
			fi
		done
	_TOKEN_
}
makePluginsCore > core/pluginscore


# Creates builder shell script
makeBuilder () {
	cat <<- _TOKEN_
	#!/bin/bash


	# Define variables for configuration
	source core/variables


	# Add plugins in codes here
	source core/pluginscore


	# Copy your theme content except theme file in building directory
	source core/themecontent


	# Make your site pages
	source core/sitepages


	# Add myimages directory to building directory
	source core/myimagescore
	_TOKEN_
}

# Save builder and make it executable and run it for the first time
makeBuilder > builder && chmod 755 builder && ./builder
